"use client";

import { useMemo, useState } from "react";
import { Banknote, Building2, CheckCircle2, CreditCard, Wallet } from "lucide-react";
import { useCollection } from "@/lib/firestore-hooks";
import { useToast } from "@/lib/toast-context";
import { useAuth } from "@/lib/auth-context";
import { computePayrollPreview, finalizePayrollRun } from "@/lib/hr";
import type { AttendanceEntry, Employee, PayrollLine, PayrollRun, SupplierPaymentMethod } from "@/lib/types";
import Drawer from "@/components/ui/Drawer";
import PillLoader from "@/components/PillLoader";

function currentPeriod() {
    return new Date().toISOString().slice(0, 7); // "2026-08"
}

function periodLabelFor(period: string) {
    return new Date(`${period}-01T00:00:00`).toLocaleDateString(undefined, { month: "long", year: "numeric" });
}

export default function PayrollPage() {
    const { data: employees, loading: l1 } = useCollection<Employee>("employees");
    const { data: attendance, loading: l2 } = useCollection<AttendanceEntry>("attendance");
    const { data: runs, loading: l3 } = useCollection<PayrollRun>("payrollRuns");
    const { user } = useAuth();
    const showToast = useToast();

    const [period, setPeriod] = useState(currentPeriod());
    const [previewing, setPreviewing] = useState(false);
    const [finalizing, setFinalizing] = useState(false);

    const existingRun = useMemo(() => runs.find((r) => r.period === period), [runs, period]);
    const history = useMemo(() => [...runs].sort((a, b) => (a.period < b.period ? 1 : -1)), [runs]);

    const preview = useMemo(() => {
        if (existingRun) return { lines: existingRun.lines, totalPayout: existingRun.totalPayout };
        return computePayrollPreview(period, employees, attendance);
    }, [existingRun, period, employees, attendance]);

    async function handleFinalize(method: SupplierPaymentMethod) {
        if (existingRun || preview.lines.length === 0) return;
        setFinalizing(true);
        try {
            await finalizePayrollRun({
                period,
                periodLabel: periodLabelFor(period),
                lines: preview.lines,
                totalPayout: preview.totalPayout,
                generatedBy: user?.email || "unknown",
                method
            });
            showToast(`Payroll finalized for ${periodLabelFor(period)} — ₹${preview.totalPayout.toLocaleString()} disbursed`);
            setPreviewing(false);
        } catch {
            showToast("Couldn't finalize payroll", "error");
        } finally {
            setFinalizing(false);
        }
    }

    if (l1 || l2 || l3) return <PillLoader label="Loading payroll…" />;

    return (
        <>
            <div className="pageHead">
                <div>
                    <h1>Payroll</h1>
                    <p>Computed straight from Attendance — flat monthlySalary / 30 per-day rate.</p>
                </div>
            </div>

            <div className="card" style={{ padding: 20, marginBottom: 20, display: "flex", alignItems: "flex-end", gap: 14, flexWrap: "wrap" }}>
                <label style={{ margin: 0 }}>Period
                    <input type="month" value={period} max={currentPeriod()} onChange={(e) => setPeriod(e.target.value)} />
                </label>
                <button className="primary" onClick={() => setPreviewing(true)} disabled={preview.lines.length === 0}>
                    {existingRun ? "View Payroll" : "Preview Payroll"}
                </button>
                {existingRun && <span className="badge completed"><i />Finalized</span>}
            </div>

            <div className="card tableCard">
                <div className="cardHead" style={{ padding: "16px 20px 0" }}><h3>Payroll History</h3></div>
                <div className="tableWrap">
                    <table>
                        <thead>
                            <tr>
                                <th>Period</th>
                                <th>Employees Paid</th>
                                <th>Total Payout</th>
                                <th>Generated By</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {history.length === 0 ? (
                                <tr><td colSpan={5}><div className="empty"><strong>No payroll runs yet</strong></div></td></tr>
                            ) : (
                                history.map((r) => (
                                    <tr key={r.id}>
                                        <td><b>{r.periodLabel}</b></td>
                                        <td>{r.lines.length}</td>
                                        <td>₹{r.totalPayout.toLocaleString()}</td>
                                        <td>{r.generatedBy}</td>
                                        <td><span className="badge completed"><i />Finalized</span></td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {previewing && (
                <Drawer
                    title={`Payroll — ${periodLabelFor(period)}`}
                    subtitle={existingRun ? `Finalized by ${existingRun.generatedBy}` : "Preview before finalizing"}
                    onClose={() => setPreviewing(false)}
                    footer={
                        existingRun ? (
                            <button type="button" onClick={() => setPreviewing(false)} style={{ width: "100%" }}>Close</button>
                        ) : (
                            <button type="button" onClick={() => setPreviewing(false)}>Cancel</button>
                        )
                    }
                >
                    <div style={{ display: "grid", gap: 12 }}>
                        {preview.lines.length === 0 ? (
                            <div className="empty"><strong>No active employees to pay</strong><br />Add employees, then mark attendance for this period.</div>
                        ) : (
                            <>
                                <div style={{ display: "grid", gap: 8 }}>
                                    {preview.lines.map((l: PayrollLine) => (
                                        <div key={l.employeeId} className="card" style={{ padding: 12, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                            <div>
                                                <strong style={{ fontSize: 13, display: "block" }}>{l.name}</strong>
                                                <span className="muted">{l.role} · {l.daysPresent}P + {l.daysHalf}H · {l.payableDays} payable days</span>
                                            </div>
                                            <strong>₹{l.grossPay.toLocaleString()}</strong>
                                        </div>
                                    ))}
                                </div>

                                <div className="card" style={{ background: "var(--dg-teal-50)", border: "1px solid var(--dg-teal-100)", display: "flex", justifyContent: "space-between", alignItems: "center", padding: 14 }}>
                                    <span style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600, color: "var(--dg-teal-700)" }}>
                                        <CheckCircle2 size={15} />Total Payout
                                    </span>
                                    <strong>₹{preview.totalPayout.toLocaleString()}</strong>
                                </div>

                                {!existingRun && (
                                    <div style={{ display: "grid", gap: 8, marginTop: 4 }}>
                                        <strong style={{ fontSize: 13 }}>Finalize &amp; disburse via</strong>
                                        <button className="pickCard" disabled={finalizing} onClick={() => handleFinalize("Cash")} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                                            <Banknote size={17} /> Cash
                                        </button>
                                        <button className="pickCard" disabled={finalizing} onClick={() => handleFinalize("Bank Transfer")} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                                            <Building2 size={17} /> Bank Transfer
                                        </button>
                                        <button className="pickCard" disabled={finalizing} onClick={() => handleFinalize("UPI")} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                                            <Wallet size={17} /> UPI
                                        </button>
                                        <button className="pickCard" disabled={finalizing} onClick={() => handleFinalize("Cheque")} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                                            <CreditCard size={17} /> Cheque
                                        </button>
                                    </div>
                                )}
                            </>
                        )}
                    </div>
                </Drawer>
            )}
        </>
    );
}
